### ISSUE TITLE
Guess-the-string writeup

### ISSUE THREAD

**Issue by Corallo** [OAlienO/CTF#2]
Hello, in this writeup:
https://github.com/OAlienO/CTF/blob/master/2018/noxCTF/Guess-The-String/README.md
you say pintool can be uesd to solve it.

Do you refer to this? 
https://github.com/ChrisTheCoolHut/PinCTF

I tried to use this tool, but it gives me a wrong solution.
Could you explain a bit more how to use this tool to win that challenge?

**Comment by oalieno** [comment]
I didn't use pintool to solve this challenge
Simply brute force one by one seems wrong
Because you can see that the first char times the second char must equal to 3478
So you need to get two char right at the same time to pass to the next check function
Maybe just reverse the binary will be easier

**Comment by Corallo** [comment]
With the argument -s you can give the initial string to the script, so I provided "J/AAAAAAAAA" as seed and with the argument -st you can choose to start bruteforcing from the 3rd char.
This should avoid the problem of the first two chars, but still, he doesn't get it.

**Comment by oalieno** [comment]
That's because you also need s[4] and s[5] to be prime and s[4] xor s[5] == 126 to pass the other check.
It depends on two variables.

**Comment by Corallo** [comment]
oh right, thank you for the clarification 👍

**Comment by oalieno** [comment]
It's my bad to state that it's solvable by pintools XD
I have modified the writeups.
